ext {
    extName = 'Shinden'
    extClass = '.Shinden'
    extVersionCode = 3
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':NewAndModifiedExtractors:MegaNz'))
    implementation(project(':NewAndModifiedExtractors:Vidara'))
    implementation(project(':NewAndModifiedExtractors:Bysesukior'))
    implementation(project(':NewAndModifiedExtractors:LycorisCafe'))
    implementation(project(':NewAndModifiedExtractors:Uqload'))
    implementation(project(':NewAndModifiedExtractors:Cda'))
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:filemoonextractor'))
    implementation(project(':lib:gdriveplayerextractor'))
    implementation(project(':NewAndModifiedExtractors:GoogleDrivePlayer'))
    implementation(project(':lib:mp4uploadextractor'))
    implementation(project(':NewAndModifiedExtractors:Okru'))
    implementation(project(':lib:sibnetextractor'))
    implementation(project(':lib:streamtapeextractor'))
    implementation(project(':lib:streamupextractor'))
    implementation(project(':lib:universalextractor'))
    implementation(project(':lib:m3u8server'))
    implementation(project(':NewAndModifiedExtractors:Flyfile'))
    implementation(project(':NewAndModifiedExtractors:ShareVideo'))
    implementation(project(':NewAndModifiedExtractors:Playmate'))
    implementation(project(':NewAndModifiedExtractors:Dailymotion'))
}
